parameters:
#    chamic_budget.example.class: Chamic\BudgetBundle\Example

services:
#    chamic_budget.example:
#        class: %chamic_budget.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
